# EmbedFile.cmake
#
# Embeds an arbitrary text file into a C/C++ header as a `static const char[]`.
#
# Unlike the classic `R"tag(...)tag"` raw-string trick, this splits the file
# into one escaped string literal PER LINE and relies on the compiler's
# adjacent-string-literal concatenation ("a" "b" == "ab"). Each individual
# literal therefore stays far below MSVC's per-literal length limit
# (raw strings and giant single literals both choke MSVC on large files),
# and the whole thing is plain portable C/C++ - no compiler extensions.
#
# Usage (script mode):
#   cmake -DINPUT=<path> -DOUTPUT=<path> -DVAR_NAME=<ident> -DGUARD=<ident>
#         -P EmbedFile.cmake
#
# Produces:
#   static const char <VAR_NAME>[] = "line1\n" "line2\n" ... ;
#   static const unsigned long <VAR_NAME>_len = sizeof(<VAR_NAME>) - 1;

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "EmbedFile.cmake: INPUT and OUTPUT must be defined")
endif()

if(NOT DEFINED VAR_NAME)
    get_filename_component(VAR_NAME "${INPUT}" NAME_WE)
    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" VAR_NAME "${VAR_NAME}")
endif()

if(NOT DEFINED GUARD)
    string(TOUPPER "${VAR_NAME}_H" GUARD)
endif()

file(READ "${INPUT}" CONTENT)

# Normalize line endings so we don't embed stray \r.
string(REPLACE "\r\n" "\n" CONTENT "${CONTENT}")

# Escape backslashes and double quotes first (order matters).
string(REPLACE "\\" "\\\\" CONTENT "${CONTENT}")
string(REPLACE "\"" "\\\"" CONTENT "${CONTENT}")

# One string literal per source line: "...\n"
# then let the compiler concatenate them.
string(REPLACE "\n" "\\n\"\n\"" CONTENT "${CONTENT}")

set(HEADER_CONTENT "// -----------------------------------------------------------------------------\n")
string(APPEND HEADER_CONTENT "// This file is AUTO-GENERATED by EmbedFile.cmake. Do not edit manually.\n")
string(APPEND HEADER_CONTENT "// Source: ${INPUT}\n")
string(APPEND HEADER_CONTENT "// -----------------------------------------------------------------------------\n\n")
string(APPEND HEADER_CONTENT "#ifndef ${GUARD}\n#define ${GUARD}\n#pragma once\n\n")
string(APPEND HEADER_CONTENT "static const char ${VAR_NAME}[] =\n\"${CONTENT}\";\n\n")
string(APPEND HEADER_CONTENT "static const unsigned long ${VAR_NAME}_len = sizeof(${VAR_NAME}) - 1;\n\n")
string(APPEND HEADER_CONTENT "#endif // ${GUARD}\n")

file(WRITE "${OUTPUT}" "${HEADER_CONTENT}")
