name: cmake stuff

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install python deps
      run: pip install pytest pytest-xdist

    - name: Build Project
      uses: threeal/cmake-action@v2.1.0
      with:
        build-dir: build
        options: |
          CMAKE_BUILD_TYPE=Release
          BUILD_PYTHON=ON

    - name: Build
      run: cmake --build build -j4 --config Release

    - name: Run tests (Linux/macOS)
      if: runner.os != 'Windows'
      run: ctest --test-dir build --output-on-failure --extra-verbose


  build-docs:
    needs: build-and-test
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.x'

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install python deps
      run: pip install doxygen-awesome-css sphinx myst-parser furo sphinx-autodoc-typehints

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_PYTHON=ON

    - name: Build documentation
      run: cmake --build build --target urlparser_docs

    - name: List docs directory
      run: find build/docs/out -maxdepth 2

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v7
      with:
        name: cmake-documentation
        path: build/docs/out
        retention-days: 5

  build-coverage:
    # needs: build-and-test
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.x'

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install python dependencies
      run: pip install pytest pytest-xdist coverage

    - name: Install coverage tools
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: Configure CMake with coverage
      run: |
        cmake -B build \
          -DBUILD_PYTHON=ON

    - name: Generate coverage report
      run: cmake --build build --target urlparser_coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: build/coverage/total/coverage.lcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v7
      with:
        name: cmake-coverage-report
        path: build/coverage/
        retention-days: 5
